export enum DashboardActionTypes {
    ADD_ORDER_TO_KITCHEN = 'ADD_ORDER_TO_KITCHEN',
    REMOVE_ORDER_FROM_KITCHEN = 'REMOVE_ORDER_FROM_KITCHEN',
    PRIORITY_ORDERS_KITCHEN = 'PRIORITY_ORDERS_KITCHEN'
}