export enum OrderActionsEnum {
    ADD_NEW_ORDER_TO_QUEUE = 'ADD_NEW_ORDER_TO_QUEUE',
    REMOVE_ORDER_FROM_QUEUE = 'REMOVE_ORDER_FROM_QUEUE',
    ADD_NEW_ORDER_TO_PRIORITY = 'ADD_NEW_ORDER_TO_PRIORITY',
    REMOVE_ORDER_FROM_PRIORITY = 'REMOVE_ORDER_FROM_PRIORITY',
    ADD_ORDER_TO_KITCHEN = 'ADD_ORDER_TO_KITCHEN',
    REMOVE_ORDER_FROM_KITCHEN = 'REMOVE_ORDER_FROM_KITCHEN',
    ADD_ORDER_TO_DELIVERY = 'ADD_ORDER_TO_DELIVERY',
    REMOVE_ORDER_FROM_DELIVERY = 'REMOVE_ORDER_FROM_DELIVERY',
    ADD_NEW_ORDER_TO_HISTORY = 'ADD_NEW_ORDER_TO_HISTORY',
    CHANGE_STATUS = 'CHANGE_STATUS'
}