export enum OrderActionsEnum {
    ADD_NEW_ORDER_TO_QUEUE = 'ADD_NEW_ORDER_TO_QUEUE',
    REMOVE_ORDER_FROM_QUEUE = 'REMOVE_ORDER_FROM_QUEUE',
    ADD_NEW_ORDER_TO_HISTORY = 'ADD_NEW_ORDER_TO_HISTORY',
    CHANGE_STATUS = 'CHANGE_STATUS',
    ORDER_CANCEL = 'ORDER_CANCEL'
}